<?php

namespace ContainerA7BxGT7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOfertaControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\OfertaController' shared autowired service.
     *
     * @return \App\Controller\Api\OfertaController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'OfertaController.php';

        $container->services['App\\Controller\\Api\\OfertaController'] = $instance = new \App\Controller\Api\OfertaController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\OfertaRepository'] ?? $container->load('getOfertaRepositoryService')), ($container->privates['App\\Repository\\ClubRepository'] ?? $container->load('getClubRepositoryService')), ($container->privates['App\\Repository\\JugadoresOfertasRepository'] ?? $container->load('getJugadoresOfertasRepositoryService')), ($container->privates['App\\Repository\\JugadorRepository'] ?? $container->load('getJugadorRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Api\\OfertaController', $container));

        return $instance;
    }
}
