<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Oferta extends \App\Entity\Oferta implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'categoria' => [parent::class, 'categoria', null, 16],
        "\0".parent::class."\0".'club' => [parent::class, 'club', null, 16],
        "\0".parent::class."\0".'descripcion' => [parent::class, 'descripcion', null, 16],
        "\0".parent::class."\0".'estado' => [parent::class, 'estado', null, 16],
        "\0".parent::class."\0".'fechaCreacion' => [parent::class, 'fechaCreacion', null, 16],
        "\0".parent::class."\0".'fechaFin' => [parent::class, 'fechaFin', null, 16],
        "\0".parent::class."\0".'fechaInicio' => [parent::class, 'fechaInicio', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'jugadores' => [parent::class, 'jugadores', null, 16],
        "\0".parent::class."\0".'titulo' => [parent::class, 'titulo', null, 16],
        'categoria' => [parent::class, 'categoria', null, 16],
        'club' => [parent::class, 'club', null, 16],
        'descripcion' => [parent::class, 'descripcion', null, 16],
        'estado' => [parent::class, 'estado', null, 16],
        'fechaCreacion' => [parent::class, 'fechaCreacion', null, 16],
        'fechaFin' => [parent::class, 'fechaFin', null, 16],
        'fechaInicio' => [parent::class, 'fechaInicio', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'jugadores' => [parent::class, 'jugadores', null, 16],
        'titulo' => [parent::class, 'titulo', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
