<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA7BxGT7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA7BxGT7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA7BxGT7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA7BxGT7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA7BxGT7\App_KernelDevDebugContainer([
    'container.build_hash' => 'A7BxGT7',
    'container.build_id' => '42b8085a',
    'container.build_time' => 1746529242,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA7BxGT7');
